language: java
services: postgresql
addons:
  ssh_known_hosts: git.balena-cloud.com
jdk:
  - openjdk8
before_script:
  - cd api
  - psql -c "CREATE DATABASE db;"
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_deploy:
  - cd $TRAVIS_BUILD_DIR
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master