version: '2'

volumes:
  db-data:
    driver: local

services:
  bjs.system.model.api:
    build: .
    depends_on:
      - bjs.system.model.db
    ports:
      - 8080:8080
  bjs.system.model.db:
    extends:
      file: docker-compose.db.yml
      service: db