version: '2'

volumes:
  db-data: {}

services:
  bjs.system.model.api:
    build: api
    depends_on:
      - bjs.system.model.db
    ports:
      - 8080:8080
  bjs.system.model.db:
    build: db
    volumes:
      - db-data:/var/lib/postgresql/10/main
    ports:
      - 5432:5432