version: '2'

volumes:
  db-data: {}

services:
  api:
    build: api
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    build: db
    volumes:
      - db-data:/var/lib/postgresql/10/main
    ports:
      - 5432:5432