server:
  port: 8080
  address: 0.0.0.0

spring:
  data:
    rest:
      base-path: /api/v1
  
  datasource:
    url: jdbc:postgresql://db:5432/db
    username: postgres
    password: bjs-org
    driver-class-name: org.postgresql.Driver
  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_default: false
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_null

logging:
  file:
    name: logs/bjs-api.log