server:
  port: 8080
  address: 0.0.0.0

spring:
  data:
    rest:
      base-path: /api/v1
  
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  
  h2:
    console:
      enabled: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  
  main:
    allow-bean-definition-overriding: true

logging:
  file:
    name: logs/bjs-api.log
  