== Classes

=== Authentication and Authorization

Only admins can create and delete classes.
To get privileges for reading and changing information look at <<_user_privileges,user privileges>>.

=== Class as an object

// TODO

=== Create new class

Only ``className`` is required for creating new classes.
But the class name has to be unique.
All other fields can optionally be defined.

operation::classes-post[snippets='request-fields,http-request,http-response']

=== Get all classes

For this request, the users only get the information they have privileges for.
Admins have rights for all users.

operation::classes-get-all[snippets='http-request,response-fields,http-response']

=== Get a single class by ID

Here, as well, the users only get to see the class they have permission for, otherwise the request will respond as `403 Forbidden`

operation::classes-get-byId[snippets='path-parameters,http-request,response-fields,http-response']

=== Get class by name

Here, as well, the users only get to see the class they have permission for, otherwise, the request will respond as `403 Forbidden`

operation::classes-get-byName[snippets='request-parameters,http-request,response-fields,http-response']

=== Get class by class teacher's name

For this request, the users only get the information they have privileges for.
Admins have rights for all users.

operation::classes-get-byTeacher[snippets='request-parameters,http-request,response-fields,http-response']

=== Edit class

Here, as well, the users only get to see the class they have permission for, otherwise, the request will respond as `403 Forbidden`
This request edits only the given fields.

operation::classes-patch[snippets='path-parameters,request-fields,http-request,response-fields,http-response']

=== Replace class

Here, as well, the users only get to see the class they have permission for, otherwise, the request will respond as `403 Forbidden`
This request replaces the whole class in contrast to `PATCH` which only changes some fields.

operation::classes-put[snippets='path-parameters,request-fields,http-request,http-response']

=== Delete class

Only admins can delete classes.

operation::classes-delete[snippets='path-parameters,http-request,http-response']