== (Sport) Results

=== Authentication and Authorization

Like at the user endpoint, the user can only edit those results which belong to the class declared at <<_user_privileges,user privileges>>.
If the user is an admin he will be able to access and modify all results.

=== Sport Result as an object

//TODO

=== Create result

operation::sport-results-post[snippets='request-fields,http-request,response-fields,http-response']

=== Get all results

operation::sport-results-get-all[snippets='http-request,response-fields,http-response']

=== Get a single result by ID

operation::sport-results-get-byId[snippets='path-parameters,http-request,response-fields,http-response']

=== Get result by student

operation::sport-results-get-byStudent-authorized[snippets='request-parameters,http-request,response-fields,http-response']

=== Get result by discipline

operation::sport-results-get-byDiscipline[snippets='request-parameters,http-request,response-fields,http-response']

=== Edit result

operation::sport-results-patch[snippets='path-parameters,request-fields,http-request,response-fields,http-response']

=== Replace result

operation::sport-results-put[snippets='path-parameters,request-fields,http-request,response-fields,http-response']

=== Delete result

operation::sport-results-delete[snippets='path-parameters,http-request,http-response']


