== Students

=== Create student

operation::students-post[snippets='request-fields,http-request,response-fields,http-response']

=== Get all students

operation::students-get-all[snippets='http-request,response-fields,http-response']

=== Get student by ID

operation::students-get-byId[snippets='path-parameters,http-request,response-fields,http-response']

=== Get students by first name

operation::students-get-byFirstName[snippets='request-parameters,http-request,response-fields,http-response']

=== Get students by last name

operation::students-get-byLastName[snippets='request-parameters,http-request,response-fields,http-response']

=== Get students by first and last name

operation::students-get-byFirstNameAndLastName[snippets='request-parameters,http-request,response-fields,http-response']

=== Edit student

operation::students-patch[snippets='path-parameters,request-fields,http-request,response-fields,http-response']

=== Replace student

operation::students-put[snippets='path-parameters,request-fields,http-request,response-fields,http-response']

=== Delete student

operation::students-delete[snippets='path-parameters,http-request,http-response']