FROM balenalib/%%BALENA_MACHINE_NAME%%-openjdk:8-jdk-latest AS build
ENV APP_HOME=/usr/src/app/
WORKDIR $APP_HOME

COPY . /usr/src/app
RUN cd /usr/src/app && ./gradlew bootJar

FROM balenalib/%%BALENA_MACHINE_NAME%%-openjdk:8-jdk-latest

COPY --from=build /usr/src/app/build/libs/* app.jar
CMD ["java","-jar","app.jar"]