name: CI

on: 
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master
      - feature/*

jobs:
  build:
    name: Gradle Build and Test
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: cd api && ./gradlew build

  deploy-balena:
    needs: [build]
    name: Deploy to Balena Cloud
    runs-on: [ubuntu-latest]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: action/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Balena Push
        uses: theaccordance/balena-push@v1.0.0
        with:
          api-token: ${{secrets.BALENA_API_TOKEN}}
          application-name: ${{secrets.BALENA_APPLICATION_NAME}}
